services:
  postgresdb:
    image: postgres:17
    container_name: postgresdb
    ports: 
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgress-seats
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
